/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Game;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dzuser
 */
public class Dados extends javax.swing.JFrame {

    /**
     * Creates new form Dados
     */
    public Dados() {
        initComponents();
        getCol();
        getBinomial();
        img(imagenes, pcks[6]);
        tabla_binomial.setModel(mod_bin);
        tabla_dados.setModel(mod_dados);
        lblfecha.setText("Hoy es "+dia(fecha)+" "+fecha.getDate()+" de "+mes(fecha)+" del año "+(fecha.getYear()+1900));
        music = new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
    
                if (!msckp.isAlive() && rmusica.isSelected()) {
                msckp.start();
                lblmusica.setText("REPRODUCIENDO MUSICA....");
                    System.out.println("ESTAMOS EN PLAY");
                }
                
                else if (msckp.isAlive() && !rmusica.isSelected()) {
                    msckp.suspend();
                    lblmusica.setText("MUSICA PAUSADA....");
                }
                
                else if (msckp.isAlive() && rmusica.isSelected() ) {
                    msckp.resume();
                    lblmusica.setText("RESUMEN DE MUSICA....");
                }
                
                else if (!msckp.isAlive() && !rmusica.isSelected()) {
                    lblmusica.setText("MUSICA TERMINADA!!!");
                }
                
            }   
        };
    rmusica.addActionListener(music);
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_binomial = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_dados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        imagenes = new javax.swing.JLabel();
        lblfecha = new javax.swing.JLabel();
        lblrnd = new javax.swing.JLabel();
        climpiar = new javax.swing.JCheckBox();
        rmusica = new javax.swing.JRadioButton();
        lblmusica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Juego de Dados BlessWare!!!");

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jLabel1.setFont(new java.awt.Font("Khmer OS System", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LANZAMIENTO DE DADOS");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 153, 255), new java.awt.Color(51, 51, 51)));

        tabla_binomial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_binomial.setToolTipText("Esta es la tabla de distribución del dado");
        jScrollPane1.setViewportView(tabla_binomial);

        jButton1.setFont(new java.awt.Font("Purisa", 1, 36)); // NOI18N
        jButton1.setText("LANZAME!!!");
        jButton1.setToolTipText("Haz click para lanzar los dados!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tabla_dados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_dados.setToolTipText("Esta es la tabla de resultados de los lanzamientos");
        jScrollPane2.setViewportView(tabla_dados);

        jPanel2.setBackground(new java.awt.Color(255, 90, 66));

        imagenes.setToolTipText("Aquí aparece la cara del dado en cuestión");
        imagenes.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 51, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenes, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenes, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );

        lblfecha.setFont(new java.awt.Font("Purisa", 2, 18)); // NOI18N
        lblfecha.setForeground(new java.awt.Color(255, 255, 0));
        lblfecha.setText("FECHA!!!");

        lblrnd.setFont(new java.awt.Font("Tlwg Typist", 2, 24)); // NOI18N
        lblrnd.setForeground(new java.awt.Color(255, 255, 255));
        lblrnd.setText("RNDi!!! ;)");
        lblrnd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.orange, java.awt.Color.darkGray, java.awt.Color.cyan, java.awt.Color.black));

        climpiar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        climpiar.setText("Limpiar");
        climpiar.setToolTipText("Limpia los datos!");
        climpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                climpiarActionPerformed(evt);
            }
        });

        rmusica.setText("Musica!");
        rmusica.setToolTipText("Escucha música!!!");

        lblmusica.setFont(new java.awt.Font("Sawasdee", 2, 14)); // NOI18N
        lblmusica.setForeground(new java.awt.Color(255, 255, 153));
        lblmusica.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblmusica.setText("Servicios Informáticos Aplicados 2016");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(lblfecha))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblrnd)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(climpiar)
                                        .addComponent(rmusica)))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblmusica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(81, 81, 81))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(lblmusica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(climpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rmusica)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblrnd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblfecha)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel mod_bin = new DefaultTableModel();
    DefaultTableModel mod_dados = new DefaultTableModel();
    int aciertos = -1;
    String [] pcks = {"/Picks/dado1.png", "/Picks/dado2.png", "/Picks/dado3.png", "/Picks/dado4.png", "/Picks/dado5.png", "/Picks/dado6.png", "/Picks/linux.jpeg"};
    int x=0;
    boolean flag_bin = true;
    Object [] bin = new Object[5];
    Date fecha = new Date();
    HiloMusical hm = new HiloMusical();
    Thread msckp = new Thread(hm, "dale"); 
    public String querola = new String();
    ActionListener music;
    Thread rolita = new Thread(hm, "rola");
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ++aciertos;
    
    double rnd=Math.random();
    
    for (int y=1; y<7; y++) {
    if (rnd >= Double.parseDouble(mod_bin.getValueAt(y-1, 3).toString()) && rnd <= Double.parseDouble(mod_bin.getValueAt(y-1, 4).toString()))
        x = y;
    
    for (int z=0; z<mod_bin.getColumnCount();z++)
        tabla_binomial.changeSelection(x-1, z, false, false);
        tabla_binomial.setSelectionBackground(Color.cyan);
        tabla_binomial.setSelectionForeground(Color.red);
        tabla_binomial.setFont(Font.decode("UnDotum-14"));
    }
    
    Date horita = new Date();
    Object [] datitosHugoleros = {aciertos, String.valueOf(rnd).substring(0,7), x, hora(horita)};
                  
    mod_dados.addRow(datitosHugoleros);
    
    for (int z=1; z < 7; z++) {
    if (x == z )
    img(imagenes, pcks[z-1]);
        }
    tabla_dados.changeSelection(aciertos, aciertos, false, false);
    lblrnd.setText("RNDi: "+String.valueOf(rnd).substring(0,7));
    this.pack();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void climpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_climpiarActionPerformed
        climpiar.setSelected(false);
        x=0;
        flag_bin=true;
        img(imagenes, pcks[6]);
        mod_dados.setNumRows(0);
        aciertos=0;
        tabla_binomial.clearSelection();
        tabla_binomial.setFont(Font.decode("Dialog"));
        this.pack();
    }//GEN-LAST:event_climpiarActionPerformed

    private void getCol() {
        
        mod_bin.addColumn("Caras");
        mod_bin.addColumn("p(x)");
        mod_bin.addColumn("P(x)");
        mod_bin.addColumn("limite inf");
        mod_bin.addColumn("limite sup");
        
        mod_dados.addColumn("Lanzamiento");
        mod_dados.addColumn("RNDi");
        mod_dados.addColumn("Resultados");
        mod_dados.addColumn("Hora");
        
    
}
    
    private int facto(int f){
        
        if (f == 0)
            return 1;
        
        else{
        int facto=1;
        while ( f!=0) {
        facto=facto*f;
        f--;
        }
        return facto; }
    }
    
    private  void img(JLabel jl, String rs) {
        jl.setIcon(new ImageIcon(getClass().getResource(rs)));
    }
    
    private String dia (Date d) {
        
        String diaHugolero = "";
        String [] diita = {"Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"};
        
        for (int x=0; x<8; x++)
            if (d.getDay() == x)
                diaHugolero = diita[x];
        
        return diaHugolero;
    }
    
    private String mes (Date d) {
        String mesesito = "";
        String [] mesHugolero = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", 
            "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"};
        
        for (int x=0; x<6; x++){
            if (d.getMonth() == x)
               mesesito = mesHugolero[x]; }
   
        return mesesito;
        
    }
    
    private String hora(Date d) {
        int horita = d.getHours();
        int minutos = d.getMinutes();
        String clas;
        
        if (horita >= 12) {
            clas = "pm";
            horita = horita-12; }
        
        else 
            clas = "am";
        
        return horita+":"+minutos+" "+clas;
    }
    
    private void getBinomial () {
        
    
        for (int a=1; a<=6; a++){
        double Px = 0;
        double lim_inf = 0;
        double a1 = 1;
        double a2 = 6;
        double px = a1/a2;
        String px1=String.valueOf(px).substring(0,7);
        double Px1 = 0;
        
        
        if (a==1)
        Px= Double.valueOf(String.valueOf(px).substring(0,7));
        
        else {
        Px1=Double.parseDouble(String.valueOf(mod_bin.getValueAt( a-2 , 2)));
        Px=Px1+px; 
        }
         
        if(a==1)
        lim_inf=0.00000;
        
        else {        
        lim_inf= (Double.parseDouble(mod_bin. getValueAt(a-2, 4).toString()));
        lim_inf=lim_inf + 0.00001;
        }
        
        if (String.valueOf(Px).length()<=6 && String.valueOf(lim_inf).length()<=6 ) {
        bin[0] = a;
        bin[1] = px1;
        bin[2] = String.valueOf(Px);
        bin[3] = String.valueOf(lim_inf);
        bin[4] = String.valueOf(Px);
        }
        
        else {
        bin[0] = a;
        bin[1] = px1;
        bin[2] = String.valueOf(Px).substring(0,7);
        bin[3] = String.valueOf(lim_inf);
        bin[4] = String.valueOf(Px).substring(0,7);    
        }
        
        mod_bin.addRow(bin);
        }
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
              Dados d = new Dados();
              d.setLocationRelativeTo(null);
              d.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox climpiar;
    private javax.swing.JLabel imagenes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblfecha;
    public javax.swing.JLabel lblmusica;
    private javax.swing.JLabel lblrnd;
    private javax.swing.JRadioButton rmusica;
    private javax.swing.JTable tabla_binomial;
    private javax.swing.JTable tabla_dados;
    // End of variables declaration//GEN-END:variables

}
